//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `CameraRGBDSimple.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __CameraRGBDSimple_h__
#define __CameraRGBDSimple_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompCameraRGBDSimple
{

class CameraRGBDSimple;
class CameraRGBDSimplePrx;

}

namespace RoboCompCameraRGBDSimple
{

class HardwareFailedException : public ::Ice::UserExceptionHelper<HardwareFailedException, ::Ice::UserException>
{
public:

    virtual ~HardwareFailedException();

    HardwareFailedException(const HardwareFailedException&) = default;

    HardwareFailedException() = default;

    /**
     * One-shot constructor to initialize all data members.
     */
    HardwareFailedException(const ::std::string& what) :
        what(::std::move(what))
    {
    }

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&> ice_tuple() const
    {
        return std::tie(what);
    }

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    ::std::string what;
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

using ImgType = ::std::vector<::Ice::Byte>;

using DepthType = ::std::vector<::Ice::Byte>;

struct TImage
{
    int cameraID;
    int width;
    int height;
    int depth;
    int focalx;
    int focaly;
    int alivetime;
    ::RoboCompCameraRGBDSimple::ImgType image;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const int&, const int&, const int&, const int&, const int&, const int&, const int&, const ::RoboCompCameraRGBDSimple::ImgType&> ice_tuple() const
    {
        return std::tie(cameraID, width, height, depth, focalx, focaly, alivetime, image);
    }
};

struct TDepth
{
    int cameraID;
    int width;
    int height;
    int focalx;
    int focaly;
    int alivetime;
    ::RoboCompCameraRGBDSimple::DepthType depth;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const int&, const int&, const int&, const int&, const int&, const int&, const ::RoboCompCameraRGBDSimple::DepthType&> ice_tuple() const
    {
        return std::tie(cameraID, width, height, focalx, focaly, alivetime, depth);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompCameraRGBDSimple
{

class CameraRGBDSimple : public virtual ::Ice::Object
{
public:

    using ProxyType = CameraRGBDSimplePrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    /**
     * Encapsulates the results of a call to getAll.
     */
    struct GetAllResult
    {
        TImage im;
        TDepth dep;
    };

    virtual void getAll(TImage& im, TDepth& dep, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getAll(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void getDepth(TDepth& dep, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getDepth(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void getImage(TImage& im, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getImage(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompCameraRGBDSimple
{

class CameraRGBDSimplePrx : public virtual ::Ice::Proxy<CameraRGBDSimplePrx, ::Ice::ObjectPrx>
{
public:

    void getAll(TImage& im, TDepth& dep, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        auto _result = _makePromiseOutgoing<CameraRGBDSimple::GetAllResult>(true, this, &CameraRGBDSimplePrx::_iceI_getAll, context).get();
        im = ::std::move(_result.im);
        dep = ::std::move(_result.dep);
    }

    template<template<typename> class P = ::std::promise>
    auto getAllAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<CameraRGBDSimple::GetAllResult>>().get_future())
    {
        return _makePromiseOutgoing<CameraRGBDSimple::GetAllResult, P>(false, this, &CameraRGBDSimplePrx::_iceI_getAll, context);
    }

    ::std::function<void()>
    getAllAsync(::std::function<void(::RoboCompCameraRGBDSimple::TImage, ::RoboCompCameraRGBDSimple::TDepth)> response,
                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                ::std::function<void(bool)> sent = nullptr,
                const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        auto _responseCb = [response](CameraRGBDSimple::GetAllResult&& _result)
        {
            response(::std::move(_result.im), ::std::move(_result.dep));
        };
        return _makeLamdaOutgoing<CameraRGBDSimple::GetAllResult>(_responseCb, ex, sent, this, &RoboCompCameraRGBDSimple::CameraRGBDSimplePrx::_iceI_getAll, context);
    }

    /// \cond INTERNAL
    void _iceI_getAll(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<CameraRGBDSimple::GetAllResult>>&, const ::Ice::Context&);
    /// \endcond

    void getDepth(TDepth& dep, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        dep = _makePromiseOutgoing<::RoboCompCameraRGBDSimple::TDepth>(true, this, &CameraRGBDSimplePrx::_iceI_getDepth, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getDepthAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompCameraRGBDSimple::TDepth>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompCameraRGBDSimple::TDepth, P>(false, this, &CameraRGBDSimplePrx::_iceI_getDepth, context);
    }

    ::std::function<void()>
    getDepthAsync(::std::function<void(::RoboCompCameraRGBDSimple::TDepth)> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompCameraRGBDSimple::TDepth>(response, ex, sent, this, &RoboCompCameraRGBDSimple::CameraRGBDSimplePrx::_iceI_getDepth, context);
    }

    /// \cond INTERNAL
    void _iceI_getDepth(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCameraRGBDSimple::TDepth>>&, const ::Ice::Context&);
    /// \endcond

    void getImage(TImage& im, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        im = _makePromiseOutgoing<::RoboCompCameraRGBDSimple::TImage>(true, this, &CameraRGBDSimplePrx::_iceI_getImage, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getImageAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompCameraRGBDSimple::TImage>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompCameraRGBDSimple::TImage, P>(false, this, &CameraRGBDSimplePrx::_iceI_getImage, context);
    }

    ::std::function<void()>
    getImageAsync(::std::function<void(::RoboCompCameraRGBDSimple::TImage)> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompCameraRGBDSimple::TImage>(response, ex, sent, this, &RoboCompCameraRGBDSimple::CameraRGBDSimplePrx::_iceI_getImage, context);
    }

    /// \cond INTERNAL
    void _iceI_getImage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCameraRGBDSimple::TImage>>&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    CameraRGBDSimplePrx() = default;
    friend ::std::shared_ptr<CameraRGBDSimplePrx> IceInternal::createProxy<CameraRGBDSimplePrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<typename S>
struct StreamReader<::RoboCompCameraRGBDSimple::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimple::HardwareFailedException& v)
    {
        istr->readAll(v.what);
    }
};

template<>
struct StreamableTraits<::RoboCompCameraRGBDSimple::TImage>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 29;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompCameraRGBDSimple::TImage, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimple::TImage& v)
    {
        istr->readAll(v.cameraID, v.width, v.height, v.depth, v.focalx, v.focaly, v.alivetime, v.image);
    }
};

template<>
struct StreamableTraits<::RoboCompCameraRGBDSimple::TDepth>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 25;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompCameraRGBDSimple::TDepth, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimple::TDepth& v)
    {
        istr->readAll(v.cameraID, v.width, v.height, v.focalx, v.focaly, v.alivetime, v.depth);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompCameraRGBDSimple
{

using CameraRGBDSimplePtr = ::std::shared_ptr<CameraRGBDSimple>;
using CameraRGBDSimplePrxPtr = ::std::shared_ptr<CameraRGBDSimplePrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompCameraRGBDSimple
{

class CameraRGBDSimple;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< CameraRGBDSimple>&);
::IceProxy::Ice::Object* upCast(CameraRGBDSimple*);
/// \endcond

}

}

namespace RoboCompCameraRGBDSimple
{

class CameraRGBDSimple;
/// \cond INTERNAL
::Ice::Object* upCast(CameraRGBDSimple*);
/// \endcond
typedef ::IceInternal::Handle< CameraRGBDSimple> CameraRGBDSimplePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple> CameraRGBDSimplePrx;
typedef CameraRGBDSimplePrx CameraRGBDSimplePrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(CameraRGBDSimplePtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompCameraRGBDSimple
{

class HardwareFailedException : public ::Ice::UserException
{
public:

    HardwareFailedException() {}
    /**
     * One-shot constructor to initialize all data members.
     */
    explicit HardwareFailedException(const ::std::string& what);
    virtual ~HardwareFailedException() throw();

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    virtual ::std::string ice_id() const;
    /**
     * Polymporphically clones this exception.
     * @return A shallow copy of this exception.
     */
    virtual HardwareFailedException* ice_clone() const;
    /**
     * Throws this exception.
     */
    virtual void ice_throw() const;

    ::std::string what;

protected:

    /// \cond STREAM
    virtual void _writeImpl(::Ice::OutputStream*) const;
    virtual void _readImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

typedef ::std::vector< ::Ice::Byte> ImgType;

typedef ::std::vector< ::Ice::Byte> DepthType;

struct TImage
{
    ::Ice::Int cameraID;
    ::Ice::Int width;
    ::Ice::Int height;
    ::Ice::Int depth;
    ::Ice::Int focalx;
    ::Ice::Int focaly;
    ::Ice::Int alivetime;
    ::RoboCompCameraRGBDSimple::ImgType image;
};

struct TDepth
{
    ::Ice::Int cameraID;
    ::Ice::Int width;
    ::Ice::Int height;
    ::Ice::Int focalx;
    ::Ice::Int focaly;
    ::Ice::Int alivetime;
    ::RoboCompCameraRGBDSimple::DepthType depth;
};

}

namespace RoboCompCameraRGBDSimple
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getAll.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getAll.
 */
class Callback_CameraRGBDSimple_getAll_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CameraRGBDSimple_getAll_Base> Callback_CameraRGBDSimple_getAllPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getDepth.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getDepth.
 */
class Callback_CameraRGBDSimple_getDepth_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CameraRGBDSimple_getDepth_Base> Callback_CameraRGBDSimple_getDepthPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getImage.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getImage.
 */
class Callback_CameraRGBDSimple_getImage_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CameraRGBDSimple_getImage_Base> Callback_CameraRGBDSimple_getImagePtr;

}

namespace IceProxy
{

namespace RoboCompCameraRGBDSimple
{

class CameraRGBDSimple : public virtual ::Ice::Proxy<CameraRGBDSimple, ::IceProxy::Ice::Object>
{
public:

    void getAll(::RoboCompCameraRGBDSimple::TImage& im, ::RoboCompCameraRGBDSimple::TDepth& dep, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_getAll(im, dep, _iceI_begin_getAll(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getAll(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getAll(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getAll(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAll(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAll(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAll(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAll(const ::RoboCompCameraRGBDSimple::Callback_CameraRGBDSimple_getAllPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAll(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAll(const ::Ice::Context& context, const ::RoboCompCameraRGBDSimple::Callback_CameraRGBDSimple_getAllPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAll(context, cb, cookie);
    }

    void end_getAll(::RoboCompCameraRGBDSimple::TImage& im, ::RoboCompCameraRGBDSimple::TDepth& dep, const ::Ice::AsyncResultPtr& result);
    /// \cond INTERNAL

    void _iceI_end_getAll(::RoboCompCameraRGBDSimple::TImage& iceP_im, ::RoboCompCameraRGBDSimple::TDepth& iceP_dep, const ::Ice::AsyncResultPtr&);
    /// \endcond

private:

    ::Ice::AsyncResultPtr _iceI_begin_getAll(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void getDepth(::RoboCompCameraRGBDSimple::TDepth& dep, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_getDepth(dep, _iceI_begin_getDepth(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getDepth(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getDepth(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getDepth(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getDepth(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getDepth(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getDepth(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getDepth(const ::RoboCompCameraRGBDSimple::Callback_CameraRGBDSimple_getDepthPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getDepth(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getDepth(const ::Ice::Context& context, const ::RoboCompCameraRGBDSimple::Callback_CameraRGBDSimple_getDepthPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getDepth(context, cb, cookie);
    }

    void end_getDepth(::RoboCompCameraRGBDSimple::TDepth& dep, const ::Ice::AsyncResultPtr& result);
    /// \cond INTERNAL

    void _iceI_end_getDepth(::RoboCompCameraRGBDSimple::TDepth& iceP_dep, const ::Ice::AsyncResultPtr&);
    /// \endcond

private:

    ::Ice::AsyncResultPtr _iceI_begin_getDepth(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void getImage(::RoboCompCameraRGBDSimple::TImage& im, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_getImage(im, _iceI_begin_getImage(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getImage(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getImage(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getImage(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getImage(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getImage(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getImage(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getImage(const ::RoboCompCameraRGBDSimple::Callback_CameraRGBDSimple_getImagePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getImage(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getImage(const ::Ice::Context& context, const ::RoboCompCameraRGBDSimple::Callback_CameraRGBDSimple_getImagePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getImage(context, cb, cookie);
    }

    void end_getImage(::RoboCompCameraRGBDSimple::TImage& im, const ::Ice::AsyncResultPtr& result);
    /// \cond INTERNAL

    void _iceI_end_getImage(::RoboCompCameraRGBDSimple::TImage& iceP_im, const ::Ice::AsyncResultPtr&);
    /// \endcond

private:

    ::Ice::AsyncResultPtr _iceI_begin_getImage(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompCameraRGBDSimple
{

class CameraRGBDSimple : public virtual ::Ice::Object
{
public:

    typedef CameraRGBDSimplePrx ProxyType;
    typedef CameraRGBDSimplePtr PointerType;

    virtual ~CameraRGBDSimple();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void getAll(TImage& im, TDepth& dep, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getAll(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void getDepth(TDepth& dep, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getDepth(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void getImage(TImage& im, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getImage(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const CameraRGBDSimple& lhs, const CameraRGBDSimple& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const CameraRGBDSimple& lhs, const CameraRGBDSimple& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompCameraRGBDSimple::HardwareFailedException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<typename S>
struct StreamWriter< ::RoboCompCameraRGBDSimple::HardwareFailedException, S>
{
    static void write(S* ostr, const ::RoboCompCameraRGBDSimple::HardwareFailedException& v)
    {
        ostr->write(v.what);
    }
};

template<typename S>
struct StreamReader< ::RoboCompCameraRGBDSimple::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimple::HardwareFailedException& v)
    {
        istr->read(v.what);
    }
};

template<>
struct StreamableTraits< ::RoboCompCameraRGBDSimple::TImage>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 29;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompCameraRGBDSimple::TImage, S>
{
    static void write(S* ostr, const ::RoboCompCameraRGBDSimple::TImage& v)
    {
        ostr->write(v.cameraID);
        ostr->write(v.width);
        ostr->write(v.height);
        ostr->write(v.depth);
        ostr->write(v.focalx);
        ostr->write(v.focaly);
        ostr->write(v.alivetime);
        ostr->write(v.image);
    }
};

template<typename S>
struct StreamReader< ::RoboCompCameraRGBDSimple::TImage, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimple::TImage& v)
    {
        istr->read(v.cameraID);
        istr->read(v.width);
        istr->read(v.height);
        istr->read(v.depth);
        istr->read(v.focalx);
        istr->read(v.focaly);
        istr->read(v.alivetime);
        istr->read(v.image);
    }
};

template<>
struct StreamableTraits< ::RoboCompCameraRGBDSimple::TDepth>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 25;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompCameraRGBDSimple::TDepth, S>
{
    static void write(S* ostr, const ::RoboCompCameraRGBDSimple::TDepth& v)
    {
        ostr->write(v.cameraID);
        ostr->write(v.width);
        ostr->write(v.height);
        ostr->write(v.focalx);
        ostr->write(v.focaly);
        ostr->write(v.alivetime);
        ostr->write(v.depth);
    }
};

template<typename S>
struct StreamReader< ::RoboCompCameraRGBDSimple::TDepth, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimple::TDepth& v)
    {
        istr->read(v.cameraID);
        istr->read(v.width);
        istr->read(v.height);
        istr->read(v.focalx);
        istr->read(v.focaly);
        istr->read(v.alivetime);
        istr->read(v.depth);
    }
};

}
/// \endcond

namespace RoboCompCameraRGBDSimple
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getAll.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getAll.
 */
template<class T>
class CallbackNC_CameraRGBDSimple_getAll : public Callback_CameraRGBDSimple_getAll_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const TImage&, const TDepth&);

    CallbackNC_CameraRGBDSimple_getAll(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimplePrx proxy = CameraRGBDSimplePrx::uncheckedCast(result->getProxy());
        TImage iceP_im;
        TDepth iceP_dep;
        try
        {
            proxy->end_getAll(iceP_im, iceP_dep, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(iceP_im, iceP_dep);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getAll.
 */
template<class T> Callback_CameraRGBDSimple_getAllPtr
newCallback_CameraRGBDSimple_getAll(const IceUtil::Handle<T>& instance, void (T::*cb)(const TImage&, const TDepth&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimple_getAll<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getAll.
 */
template<class T> Callback_CameraRGBDSimple_getAllPtr
newCallback_CameraRGBDSimple_getAll(T* instance, void (T::*cb)(const TImage&, const TDepth&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimple_getAll<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getAll.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getAll.
 */
template<class T, typename CT>
class Callback_CameraRGBDSimple_getAll : public Callback_CameraRGBDSimple_getAll_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const TImage&, const TDepth&, const CT&);

    Callback_CameraRGBDSimple_getAll(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimplePrx proxy = CameraRGBDSimplePrx::uncheckedCast(result->getProxy());
        TImage iceP_im;
        TDepth iceP_dep;
        try
        {
            proxy->end_getAll(iceP_im, iceP_dep, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(iceP_im, iceP_dep, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getAll.
 */
template<class T, typename CT> Callback_CameraRGBDSimple_getAllPtr
newCallback_CameraRGBDSimple_getAll(const IceUtil::Handle<T>& instance, void (T::*cb)(const TImage&, const TDepth&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimple_getAll<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getAll.
 */
template<class T, typename CT> Callback_CameraRGBDSimple_getAllPtr
newCallback_CameraRGBDSimple_getAll(T* instance, void (T::*cb)(const TImage&, const TDepth&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimple_getAll<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getDepth.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getDepth.
 */
template<class T>
class CallbackNC_CameraRGBDSimple_getDepth : public Callback_CameraRGBDSimple_getDepth_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const TDepth&);

    CallbackNC_CameraRGBDSimple_getDepth(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimplePrx proxy = CameraRGBDSimplePrx::uncheckedCast(result->getProxy());
        TDepth iceP_dep;
        try
        {
            proxy->end_getDepth(iceP_dep, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(iceP_dep);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getDepth.
 */
template<class T> Callback_CameraRGBDSimple_getDepthPtr
newCallback_CameraRGBDSimple_getDepth(const IceUtil::Handle<T>& instance, void (T::*cb)(const TDepth&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimple_getDepth<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getDepth.
 */
template<class T> Callback_CameraRGBDSimple_getDepthPtr
newCallback_CameraRGBDSimple_getDepth(T* instance, void (T::*cb)(const TDepth&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimple_getDepth<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getDepth.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getDepth.
 */
template<class T, typename CT>
class Callback_CameraRGBDSimple_getDepth : public Callback_CameraRGBDSimple_getDepth_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const TDepth&, const CT&);

    Callback_CameraRGBDSimple_getDepth(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimplePrx proxy = CameraRGBDSimplePrx::uncheckedCast(result->getProxy());
        TDepth iceP_dep;
        try
        {
            proxy->end_getDepth(iceP_dep, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(iceP_dep, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getDepth.
 */
template<class T, typename CT> Callback_CameraRGBDSimple_getDepthPtr
newCallback_CameraRGBDSimple_getDepth(const IceUtil::Handle<T>& instance, void (T::*cb)(const TDepth&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimple_getDepth<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getDepth.
 */
template<class T, typename CT> Callback_CameraRGBDSimple_getDepthPtr
newCallback_CameraRGBDSimple_getDepth(T* instance, void (T::*cb)(const TDepth&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimple_getDepth<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getImage.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getImage.
 */
template<class T>
class CallbackNC_CameraRGBDSimple_getImage : public Callback_CameraRGBDSimple_getImage_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const TImage&);

    CallbackNC_CameraRGBDSimple_getImage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimplePrx proxy = CameraRGBDSimplePrx::uncheckedCast(result->getProxy());
        TImage iceP_im;
        try
        {
            proxy->end_getImage(iceP_im, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(iceP_im);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getImage.
 */
template<class T> Callback_CameraRGBDSimple_getImagePtr
newCallback_CameraRGBDSimple_getImage(const IceUtil::Handle<T>& instance, void (T::*cb)(const TImage&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimple_getImage<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getImage.
 */
template<class T> Callback_CameraRGBDSimple_getImagePtr
newCallback_CameraRGBDSimple_getImage(T* instance, void (T::*cb)(const TImage&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimple_getImage<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getImage.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimple::newCallback_CameraRGBDSimple_getImage.
 */
template<class T, typename CT>
class Callback_CameraRGBDSimple_getImage : public Callback_CameraRGBDSimple_getImage_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const TImage&, const CT&);

    Callback_CameraRGBDSimple_getImage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimplePrx proxy = CameraRGBDSimplePrx::uncheckedCast(result->getProxy());
        TImage iceP_im;
        try
        {
            proxy->end_getImage(iceP_im, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(iceP_im, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getImage.
 */
template<class T, typename CT> Callback_CameraRGBDSimple_getImagePtr
newCallback_CameraRGBDSimple_getImage(const IceUtil::Handle<T>& instance, void (T::*cb)(const TImage&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimple_getImage<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimple::CameraRGBDSimple::begin_getImage.
 */
template<class T, typename CT> Callback_CameraRGBDSimple_getImagePtr
newCallback_CameraRGBDSimple_getImage(T* instance, void (T::*cb)(const TImage&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimple_getImage<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
