//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `CameraRGBDSimpleYoloPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <CameraRGBDSimpleYoloPub.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub"
};
const ::std::string iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "pushRGBDYolo"
};
const ::std::string iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_pushRGBDYolo_name = "pushRGBDYolo";

}

bool
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids, iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids + 2, s);
}

::std::vector<::std::string>
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids[0], &iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids[2]);
}

::std::string
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::_iceD_pushRGBDYolo(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Idempotent, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompCameraRGBDSimple::TImage iceP_im;
    ::RoboCompCameraRGBDSimple::TDepth iceP_dep;
    ::RoboCompYoloServer::Objects iceP_objs;
    istr->readAll(iceP_im, iceP_dep, iceP_objs);
    inS.endReadParams();
    this->pushRGBDYolo(::std::move(iceP_im), ::std::move(iceP_dep), ::std::move(iceP_objs), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ops, iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_pushRGBDYolo(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPubPrx::_iceI_pushRGBDYolo(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompCameraRGBDSimple::TImage& iceP_im, const ::RoboCompCameraRGBDSimple::TDepth& iceP_dep, const ::RoboCompYoloServer::Objects& iceP_objs, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_pushRGBDYolo_name, ::Ice::OperationMode::Idempotent, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_im, iceP_dep, iceP_objs);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPubPrx::_newInstance() const
{
    return ::IceInternal::createProxy<CameraRGBDSimpleYoloPubPrx>();
}
/// \endcond

const ::std::string&
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPubPrx::ice_staticId()
{
    return CameraRGBDSimpleYoloPub::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_pushRGBDYolo_name = "pushRGBDYolo";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompCameraRGBDSimpleYoloPub::upCast(CameraRGBDSimpleYoloPub* p) { return p; }

void
::IceProxy::RoboCompCameraRGBDSimpleYoloPub::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< CameraRGBDSimpleYoloPub>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new CameraRGBDSimpleYoloPub;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::_iceI_begin_pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& iceP_im, const ::RoboCompCameraRGBDSimple::TDepth& iceP_dep, const ::RoboCompYoloServer::Objects& iceP_objs, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_pushRGBDYolo_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_pushRGBDYolo_name, ::Ice::Idempotent, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_im);
        ostr->write(iceP_dep);
        ostr->write(iceP_objs);
        result->endWriteParams();
        result->invoke(iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_pushRGBDYolo_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::end_pushRGBDYolo(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_pushRGBDYolo_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::_newInstance() const
{
    return new CameraRGBDSimpleYoloPub;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_staticId()
{
    return ::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_staticId();
}

RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::~CameraRGBDSimpleYoloPub()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompCameraRGBDSimpleYoloPub::upCast(CameraRGBDSimpleYoloPub* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub"
};

}

bool
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids, iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids[0], &iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids[2]);
}

const ::std::string&
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub";
    return typeId;
#else
    return iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::_iceD_pushRGBDYolo(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Idempotent, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompCameraRGBDSimple::TImage iceP_im;
    ::RoboCompCameraRGBDSimple::TDepth iceP_dep;
    ::RoboCompYoloServer::Objects iceP_objs;
    istr->read(iceP_im);
    istr->read(iceP_dep);
    istr->read(iceP_objs);
    inS.endReadParams();
    this->pushRGBDYolo(iceP_im, iceP_dep, iceP_objs, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "pushRGBDYolo"
};

}

/// \cond INTERNAL
bool
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_all, iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompCameraRGBDSimpleYoloPub_CameraRGBDSimpleYoloPub_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_pushRGBDYolo(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< CameraRGBDSimpleYoloPub, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< CameraRGBDSimpleYoloPub, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompCameraRGBDSimpleYoloPub::_icePatchObjectPtr(CameraRGBDSimpleYoloPubPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = CameraRGBDSimpleYoloPubPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(CameraRGBDSimpleYoloPub::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
