//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `CameraRGBDSimpleYoloPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __CameraRGBDSimpleYoloPub_h__
#define __CameraRGBDSimpleYoloPub_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <YoloServer.h>
#include <CameraRGBDSimple.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompCameraRGBDSimpleYoloPub
{

class CameraRGBDSimpleYoloPub;
class CameraRGBDSimpleYoloPubPrx;

}

namespace RoboCompCameraRGBDSimpleYoloPub
{

class CameraRGBDSimpleYoloPub : public virtual ::Ice::Object
{
public:

    using ProxyType = CameraRGBDSimpleYoloPubPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void pushRGBDYolo(::RoboCompCameraRGBDSimple::TImage im, ::RoboCompCameraRGBDSimple::TDepth dep, ::RoboCompYoloServer::Objects objs, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_pushRGBDYolo(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompCameraRGBDSimpleYoloPub
{

class CameraRGBDSimpleYoloPubPrx : public virtual ::Ice::Proxy<CameraRGBDSimpleYoloPubPrx, ::Ice::ObjectPrx>
{
public:

    void pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &CameraRGBDSimpleYoloPubPrx::_iceI_pushRGBDYolo, im, dep, objs, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto pushRGBDYoloAsync(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &CameraRGBDSimpleYoloPubPrx::_iceI_pushRGBDYolo, im, dep, objs, context);
    }

    ::std::function<void()>
    pushRGBDYoloAsync(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs,
                      ::std::function<void()> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPubPrx::_iceI_pushRGBDYolo, im, dep, objs, context);
    }

    /// \cond INTERNAL
    void _iceI_pushRGBDYolo(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompCameraRGBDSimple::TImage&, const ::RoboCompCameraRGBDSimple::TDepth&, const ::RoboCompYoloServer::Objects&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    CameraRGBDSimpleYoloPubPrx() = default;
    friend ::std::shared_ptr<CameraRGBDSimpleYoloPubPrx> IceInternal::createProxy<CameraRGBDSimpleYoloPubPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompCameraRGBDSimpleYoloPub
{

using CameraRGBDSimpleYoloPubPtr = ::std::shared_ptr<CameraRGBDSimpleYoloPub>;
using CameraRGBDSimpleYoloPubPrxPtr = ::std::shared_ptr<CameraRGBDSimpleYoloPubPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompCameraRGBDSimpleYoloPub
{

class CameraRGBDSimpleYoloPub;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< CameraRGBDSimpleYoloPub>&);
::IceProxy::Ice::Object* upCast(CameraRGBDSimpleYoloPub*);
/// \endcond

}

}

namespace RoboCompCameraRGBDSimpleYoloPub
{

class CameraRGBDSimpleYoloPub;
/// \cond INTERNAL
::Ice::Object* upCast(CameraRGBDSimpleYoloPub*);
/// \endcond
typedef ::IceInternal::Handle< CameraRGBDSimpleYoloPub> CameraRGBDSimpleYoloPubPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub> CameraRGBDSimpleYoloPubPrx;
typedef CameraRGBDSimpleYoloPubPrx CameraRGBDSimpleYoloPubPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(CameraRGBDSimpleYoloPubPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompCameraRGBDSimpleYoloPub
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleYoloPub::newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo.
 */
class Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo_Base> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr;

}

namespace IceProxy
{

namespace RoboCompCameraRGBDSimpleYoloPub
{

class CameraRGBDSimpleYoloPub : public virtual ::Ice::Proxy<CameraRGBDSimpleYoloPub, ::IceProxy::Ice::Object>
{
public:

    void pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_pushRGBDYolo(_iceI_begin_pushRGBDYolo(im, dep, objs, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_pushRGBDYolo(im, dep, objs, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_pushRGBDYolo(im, dep, objs, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_pushRGBDYolo(im, dep, objs, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::RoboCompCameraRGBDSimpleYoloPub::Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_pushRGBDYolo(im, dep, objs, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::Ice::Context& context, const ::RoboCompCameraRGBDSimpleYoloPub::Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_pushRGBDYolo(im, dep, objs, context, cb, cookie);
    }

    void end_pushRGBDYolo(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage&, const ::RoboCompCameraRGBDSimple::TDepth&, const ::RoboCompYoloServer::Objects&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompCameraRGBDSimpleYoloPub
{

class CameraRGBDSimpleYoloPub : public virtual ::Ice::Object
{
public:

    typedef CameraRGBDSimpleYoloPubPrx ProxyType;
    typedef CameraRGBDSimpleYoloPubPtr PointerType;

    virtual ~CameraRGBDSimpleYoloPub();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void pushRGBDYolo(const ::RoboCompCameraRGBDSimple::TImage& im, const ::RoboCompCameraRGBDSimple::TDepth& dep, const ::RoboCompYoloServer::Objects& objs, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_pushRGBDYolo(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const CameraRGBDSimpleYoloPub& lhs, const CameraRGBDSimpleYoloPub& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const CameraRGBDSimpleYoloPub& lhs, const CameraRGBDSimpleYoloPub& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

namespace RoboCompCameraRGBDSimpleYoloPub
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleYoloPub::newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo.
 */
template<class T>
class CallbackNC_CameraRGBDSimpleYoloPub_pushRGBDYolo : public Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_CameraRGBDSimpleYoloPub_pushRGBDYolo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 */
template<class T> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr
newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleYoloPub_pushRGBDYolo<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 */
template<class T> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr
newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleYoloPub_pushRGBDYolo<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 */
template<class T> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr
newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleYoloPub_pushRGBDYolo<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 */
template<class T> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr
newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleYoloPub_pushRGBDYolo<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleYoloPub::newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo.
 */
template<class T, typename CT>
class Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo : public Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr
newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr
newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr
newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleYoloPub::CameraRGBDSimpleYoloPub::begin_pushRGBDYolo.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleYoloPub_pushRGBDYoloPtr
newCallback_CameraRGBDSimpleYoloPub_pushRGBDYolo(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleYoloPub_pushRGBDYolo<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
